//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by BG3ModStudio.rc
//
#define ID_SEPARATOR                    0
#define ID_DEFAULT_PANE                 0
#define IDR_MAINFRAME                   101
#define IDI_FOLDER                      102
#define IDI_FILE                        103
#define ID_TOOL_PACKAGE                 104
#define IDR_TAB_CONTEXT                 105
#define IDR_TREE_CONTEXT                106
#define ID_FILE_SAVE_ALL                107
#define IDI_NOBOM                       108
#define IDI_BOM                         109
#define ID_TOOL_LOCA                    110
#define IDD_INDEX                       111
#define ID_TOOL_INDEX                   112
#define ID_TOOL_SEARCH                  113
#define IDD_SEARCH                      114
#define IDC_B_SEARCH                    115
#define IDC_B_BROWSE                    116
#define IDC_E_QUERY                     117
#define IDC_E_FOLDER                    118
#define IDC_B_BROWSE_INDEX              119
#define IDD_ATTRIBUTES                  120
#define IDC_B_BROWSE_GAMEOBJECT         121
#define IDC_B_BROWSE_GAME               122
#define ID_TOOL_SETTINGS                123
#define IDC_B_BROWSE_ICON               124
#define IDD_SETTINGS                    125
#define IDC_E_INDEX_FOLDER              126
#define IDC_E_GAMEOBJECT_FOLDER         127
#define ID_TOOL_LSF                     128
#define IDC_E_GAME_FOLDER               129
#define IDR_ATTRIBUTE_CONTEXT           130
#define IDC_E_ICON_FOLDER               131
#define ID_TOOL_GAMEOBJECT              132
#define IDD_GAMEOBJECT                  133
#define IDD_ICON_EXPLORER               134
#define ID_TOOL_ICON_EXPLORER           135
#define IDD_ICON                        136
#define IDD_PAKWIZ_WELCOME              137
#define IDB_PAK_HEADER                  138
#define IDB_PAK_LARGE                   139
#define IDD_PAKWIZ_FILE                 140
#define IDD_PAKWIZ_BUILD                141
#define IDD_UUID                        142
#define ID_TOOL_UUID                    143
#define IDR_VALUE_CONTEXT               144
#define IDR_ENTRY_CONTEXT               145
#define IDI_REGION                      146
#define IDI_NODE                        147
#define IDD_PAK_EXPLORER                148
#define ID_FILE_PAK_OPEN                149
#define ID_TOOL_BG3                     150
#define IDD_ABOUT                       151
#define ID_FILE_RECENT_FILES            152
#define IDD_NEW_PROJECT                 153
#define ID_FILE_NEW_FOLDER              154
#define IDD_NEW_PROJECT_FOLDER          155
#define IDB_NEW_PROJECT_LARGE           156
#define IDD_NEW_PROJECT_BUILD           157
#define IDR_META_TEMPLATE               158
#define IDR_LOCA_TEMPLATE               159
#define IDR_ROOT_TEMPLATES_TEMPLATE     160
#define IDR_TREASURE_TEMPLATE           161
#define IDD_FIND_REPLACE                162
#define ID_TOOL_FIND_REPLACE            163
#define IDD_VALUE_VIEW                  164
#define IDD_DB                          165
#define ID_TOOL_DB                      166
#define IDI_GAME_OBJECT                 167
#define IDR_PAK_CONTEXT                 168
#define IDR_LICENSE                     169
#define IDI_GOAL                        170
#define IDI_CALL                        171
#define IDI_DATABASE                    173
#define IDD_TYPE_VIEW                   174
#define IDI_FOLDER_SMALL                178
#define IDD_GOAL_VIEW                   179
#define IDD_FUNCTION_VIEW               180
#define IDI_FUNCTION                    181
#define IDI_TYPES                       182
#define IDD_FORMVIEW                    183
#define IDD_DB_VIEW                     184
#define IDI_ENUM                        186
#define IDC_PROGRESS_INDEX              1000
#define IDC_PAKFILE                     1001
#define IDC_INDEX_FILE                  1002
#define IDC_INDEX_STATUS                1003
#define IDC_E_PAKFILE                   1004
#define IDC_B_PAKFILE                   1005
#define IDC_INDEXPATH                   1006
#define IDC_E_INDEXPATH                 1007
#define IDC_B_INDEXPATH                 1008
#define IDC_CHK_OVERWRITE               1009
#define IDC_LST_RESULTS                 1010
#define IDC_LST_ATTRIBUTES              1011
#define IDC_B_FIRST                     1012
#define IDC_B_PREV                      1013
#define IDC_B_NEXT                      1014
#define IDC_B_LAST                      1015
#define IDC_PAGEINFO                    1016
#define IDC_ST_GAMEOBJECT               1019
#define IDC_E_QUERY_ICON                1027
#define IDC_B_SEARCH_ICON               1028
#define IDC_B_ICON_FIRST_PAGE           1029
#define IDC_B_ICON_PREV_PAGE            1030
#define IDC_B_ICON_NEXT_PAGE            1031
#define IDC_B_ICON_LAST_PAGE            1032
#define IDC_ICON_PAGEINFO               1033
#define IDC_ST_ICON_EXPLORER            1034
#define IDC_ST_ICON                     1035
#define IDC_PAKWIZ_TITLE                1036
#define IDC_PAKWIZ_PROGRESS             1037
#define IDC_CHK_GENERATE_LOCA           1038
#define IDC_CHK_GENERATE_LSF            1039
#define IDC_E_PAK_BUILDER               1040
#define IDC_B_PAK_BUILDER_BROWSE        1041
#define IDC_PROGRESS_PAKWIZ             1042
#define IDC_ST_UUID                     1043
#define IDC_GENERATE_UUID               1044
#define IDC_CHK_UUID_HANDLE             1045
#define IDC_ST_PAKEXPLORER              1046
#define IDC_APPNAME                     1047
#define IDC_COPYRIGHT                   1048
#define IDC_NOTICE                      1049
#define IDC_VERSION                     1050
#define IDC_APPICON                     1051
#define IDC_CB_COMPRESSION              1052
#define IDC_NEW_PROJECT_TITLE           1053
#define IDC_E_NEW_FOLDER                1054
#define IDC_B_NEW_PROJECT_BROWSE        1055
#define IDC_PROGRESS_NEW_PROJECT        1056
#define IDC_E_MOD_NAME                  1057
#define IDC_E_AUTHOR_NAME               1058
#define IDC_CHK_OPEN_NEW_PROJECT        1059
#define IDC_E_FIND                      1060
#define IDC_E_REPLACE                   1061
#define IDC_B_MATCHCASE                 1062
#define IDC_B_WHOLEWORD                 1063
#define IDC_B_REGEX                     1064
#define IDC_B_REPLACE                   1065
#define IDC_B_REPLACE_ALL               1066
#define IDC_B_FIND_NEXT                 1067
#define IDC_E_VALUE                     1069
#define IDC_E_SIGNATURE                 1070
#define IDC_DECOMPILED                  1071
#define IDC_DBPATH                      1072
#define IDC_PROGRESS_DB                 1073
#define IDC_E_DBPATH                    1074
#define IDC_RADIO_GAMEOBJECT            1076
#define IDC_RADIO_ICON                  1077
#define IDC_B_DBPATH                    1078
#define IDC_DB_STATUS                   1079
#define IDC_LICENSE                     1080
#define IDC_B_LICENSE                   1080
#define IDC_LICENSE_TEXT                1081
#define IDC_INIT_CALLS                  1084
#define IDC_EXIT_CALLS                  1085
#define IDC_FUNCTION_TYPE               1086
#define IDC_TYPE                        1087
#define IDC_ALIAS                       1088
#define IDC_LST_DATABASE                1098
#define ATL_IDC_TAB_CONTROL             0x3020
#define ID_APPLY_NOW                    0x3021
#define ID_WIZBACK                      0x3023
#define ID_WIZNEXT                      0x3024
#define ID_WIZFINISH                    0x3025
#define ID_TAB_CLOSE                    40007
#define ID_TAB_CLOSE_ALL                40008
#define ID_TAB_CLOSE_OTHERS             40009
#define ID_TREE_NEWFILEHERE             40010
#define ID_TREE_DELETE_FILE             40011
#define ID_TREE_MAKELSFHERE             40017
#define ID_TREE_DELETE_FOLDER           40018
#define ID_ATTRIBUTE_COPYNAME           40019
#define ID_ATTRIBUTE_COPYVALUE          40020
#define ID_ATTRIBUTE_COPYTYPE           40021
#define ID_UUID_LIST                    40022
#define ID_ATTRIBUTE_LIST               40023
#define ID_ICON_VIEW                    40024
#define ID_ICON_LIST                    40025
#define ID_ATTRIBUTE                    40026
#define ID_ATTRIBUTEMENU                40027
#define ID_ATTRIBUTE_COPYENTRY          40028
#define ID_ENTRY_COPYENTRY              40029
#define ID_VALUE_COPYVALUE              40030
#define ID_TREE_NEWFOLDERHERE           40031
#define ID_TREE_RENAME_FILE             40032
#define ID_ATTRIBUTE_VIEWVALUE          40034
#define ID_ATTRIBUTE_VIEW_VALUE         40035
#define ID_PAK_EXTRACT_FILE             40036
#define ATL_IDS_IDLEMESSAGE             0xE001
#define ID_FILE_NEW                     0xE100
#define ID_FILE_OPEN                    0xE101
#define ID_FILE_CLOSE                   0xE102
#define ID_FILE_SAVE                    0xE103
#define ID_FILE_SAVE_AS                 0xE104
#define ID_FILE_PAGE_SETUP              0xE105
#define ID_FILE_PRINT_SETUP             0xE106
#define ID_FILE_PRINT                   0xE107
#define ID_FILE_PRINT_DIRECT            0xE108
#define ID_FILE_PRINT_PREVIEW           0xE109
#define ID_FILE_UPDATE                  0xE10A
#define ID_FILE_SAVE_COPY_AS            0xE10B
#define ID_FILE_SEND_MAIL               0xE10C
#define ID_FILE_MRU_FIRST               0xE110
#define ID_FILE_MRU_FILE1               0xE110
#define ID_FILE_MRU_FILE2               0xE111
#define ID_FILE_MRU_FILE3               0xE112
#define ID_FILE_MRU_FILE4               0xE113
#define ID_FILE_MRU_FILE5               0xE114
#define ID_FILE_MRU_FILE6               0xE115
#define ID_FILE_MRU_FILE7               0xE116
#define ID_FILE_MRU_FILE8               0xE117
#define ID_FILE_MRU_FILE9               0xE118
#define ID_FILE_MRU_FILE10              0xE119
#define ID_FILE_MRU_FILE11              0xE11A
#define ID_FILE_MRU_FILE12              0xE11B
#define ID_FILE_MRU_FILE13              0xE11C
#define ID_FILE_MRU_FILE14              0xE11D
#define ID_FILE_MRU_FILE15              0xE11E
#define ID_FILE_MRU_FILE16              0xE11F
#define ID_FILE_MRU_LAST                0xE11F
#define ID_EDIT_CLEAR                   0xE120
#define ID_EDIT_CLEAR_ALL               0xE121
#define ID_EDIT_COPY                    0xE122
#define ID_EDIT_CUT                     0xE123
#define ID_EDIT_FIND                    0xE124
#define ID_EDIT_PASTE                   0xE125
#define ID_EDIT_PASTE_LINK              0xE126
#define ID_EDIT_PASTE_SPECIAL           0xE127
#define ID_EDIT_REPEAT                  0xE128
#define ID_EDIT_REPLACE                 0xE129
#define ID_EDIT_SELECT_ALL              0xE12A
#define ID_EDIT_UNDO                    0xE12B
#define ID_EDIT_REDO                    0xE12C
#define ID_EDIT_FIND_PREVIOUS           0xE12D
#define ID_WINDOW_NEW                   0xE130
#define ID_WINDOW_ARRANGE               0xE131
#define ID_WINDOW_CASCADE               0xE132
#define ID_WINDOW_TILE_HORZ             0xE133
#define ID_WINDOW_TILE_VERT             0xE134
#define ID_WINDOW_SPLIT                 0xE135
#define ID_APP_ABOUT                    0xE140
#define ID_APP_EXIT                     0xE141
#define ID_HELP_INDEX                   0xE142
#define ID_HELP_FINDER                  0xE143
#define ID_HELP_USING                   0xE144
#define ID_CONTEXT_HELP                 0xE145
#define ID_HELP                         0xE146
#define ID_DEFAULT_HELP                 0xE147
#define ID_NEXT_PANE                    0xE150
#define ID_PREV_PANE                    0xE151
#define ID_PANE_CLOSE                   0xE152
#define ID_FORMAT_FONT                  0xE160
#define ID_SCROLL_UP                    0xE170
#define ID_SCROLL_DOWN                  0xE171
#define ID_SCROLL_PAGE_UP               0xE172
#define ID_SCROLL_PAGE_DOWN             0xE173
#define ID_SCROLL_TOP                   0xE174
#define ID_SCROLL_BOTTOM                0xE175
#define ID_SCROLL_LEFT                  0xE176
#define ID_SCROLL_RIGHT                 0xE177
#define ID_SCROLL_PAGE_LEFT             0xE178
#define ID_SCROLL_PAGE_RIGHT            0xE179
#define ID_SCROLL_ALL_LEFT              0xE17A
#define ID_SCROLL_ALL_RIGHT             0xE17B
#define ID_OLE_INSERT_NEW               0xE200
#define ID_OLE_EDIT_LINKS               0xE201
#define ID_OLE_EDIT_CONVERT             0xE202
#define ID_OLE_EDIT_CHANGE_ICON         0xE203
#define ID_OLE_EDIT_PROPERTIES          0xE204
#define ID_OLE_VERB_FIRST               0xE210
#define ID_VIEW_TOOLBAR                 0xE800
#define ID_VIEW_STATUS_BAR              0xE801
#define ID_VIEW_REFRESH                 0xE803
#define ID_VIEW_RIBBON                  0xE804
#define ATL_IDS_SCSIZE                  0xEF00
#define ATL_IDS_SCMOVE                  0xEF01
#define ATL_IDS_SCMINIMIZE              0xEF02
#define ATL_IDS_SCMAXIMIZE              0xEF03
#define ATL_IDS_SCNEXTWINDOW            0xEF04
#define ATL_IDS_SCPREVWINDOW            0xEF05
#define ATL_IDS_SCCLOSE                 0xEF06
#define ATL_IDS_SCRESTORE               0xEF12
#define ATL_IDS_SCTASKLIST              0xEF13
#define ATL_IDS_MDICHILD                0xEF1F
#define ATL_IDS_MRU_FILE                0xEFDA
#define ID_WINDOW_TABFIRST              0xFF00
#define ID_WINDOW_TABLAST               0xFFFD
#define ID_WINDOW_SHOWTABLIST           0xFFFE

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        187
#define _APS_NEXT_COMMAND_VALUE         40037
#define _APS_NEXT_CONTROL_VALUE         1099
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
