// *****************************************************************************
// * This is an automatically generated header file for UI Element definition  *
// * resource symbols and values. Please do not modify manually.               *
// *****************************************************************************

#pragma once

#define ID_FILE_NEW 0xE100 
#define ID_FILE_NEW_LabelTitle_RESID 60001
#define ID_FILE_NEW_Keytip_RESID 60002
#define ID_FILE_NEW_TooltipTitle_RESID 60003
#define ID_FILE_NEW_TooltipDescription_RESID 60004
#define ID_FILE_OPEN 0xE101 
#define ID_FILE_OPEN_LabelTitle_RESID 60005
#define ID_FILE_OPEN_Keytip_RESID 60006
#define ID_FILE_OPEN_TooltipTitle_RESID 60007
#define ID_FILE_OPEN_TooltipDescription_RESID 60008
#define ID_FILE_CLOSE 0xE102 
#define ID_FILE_CLOSE_LabelTitle_RESID 60009
#define ID_FILE_CLOSE_Keytip_RESID 60010
#define ID_FILE_CLOSE_TooltipTitle_RESID 60011
#define ID_FILE_CLOSE_TooltipDescription_RESID 60012
#define ID_TOOL_PACKAGE 104 
#define ID_TOOL_PACKAGE_LabelTitle_RESID 60013
#define ID_TOOL_PACKAGE_Keytip_RESID 60014
#define ID_TOOL_PACKAGE_TooltipTitle_RESID 60015
#define ID_TOOL_PACKAGE_TooltipDescription_RESID 60016
#define ID_FILE_SAVE 0xE103 
#define ID_FILE_SAVE_LabelTitle_RESID 60017
#define ID_FILE_SAVE_Keytip_RESID 60018
#define ID_FILE_SAVE_TooltipTitle_RESID 60019
#define ID_FILE_SAVE_TooltipDescription_RESID 60020
#define ID_FILE_SAVE_ALL 0x6C 
#define ID_FILE_SAVE_ALL_LabelTitle_RESID 60021
#define ID_FILE_SAVE_ALL_Keytip_RESID 60022
#define ID_FILE_SAVE_ALL_TooltipTitle_RESID 60023
#define ID_FILE_SAVE_ALL_TooltipDescription_RESID 60024
#define ID_TOOL_LOCA 114 
#define ID_TOOL_LOCA_LabelTitle_RESID 60025
#define ID_TOOL_LOCA_Keytip_RESID 60026
#define ID_TOOL_LOCA_TooltipTitle_RESID 60027
#define ID_TOOL_LOCA_TooltipDescription_RESID 60028
#define ID_TOOL_INDEX 117 
#define ID_TOOL_INDEX_LabelTitle_RESID 60029
#define ID_TOOL_INDEX_Keytip_RESID 60030
#define ID_TOOL_INDEX_TooltipTitle_RESID 60031
#define ID_TOOL_INDEX_TooltipDescription_RESID 60032
#define ID_TOOL_SEARCH 118 
#define ID_TOOL_SEARCH_LabelTitle_RESID 60033
#define ID_TOOL_SEARCH_Keytip_RESID 60034
#define ID_TOOL_SEARCH_TooltipTitle_RESID 60035
#define ID_TOOL_SEARCH_TooltipDescription_RESID 60036
#define ID_APP_ABOUT 0xE140 
#define ID_APP_ABOUT_LabelTitle_RESID 60037
#define ID_APP_ABOUT_Keytip_RESID 60038
#define ID_APP_ABOUT_TooltipTitle_RESID 60039
#define ID_APP_ABOUT_TooltipDescription_RESID 60040
#define ID_VIEW_OUTPUT 0xE802 
#define ID_VIEW_OUTPUT_LabelTitle_RESID 60041
#define ID_VIEW_OUTPUT_Keytip_RESID 60042
#define ID_VIEW_OUTPUT_TooltipTitle_RESID 60043
#define ID_VIEW_OUTPUT_TooltipDescription_RESID 60044
#define ID_VIEW_STATUS_BAR 0xE801 
#define ID_APP_EXIT 0xE141 
#define ID_TAB_HOME 2 
#define ID_TAB_HOME_LabelTitle_RESID 60045
#define ID_TAB_TOOLS 3 
#define ID_TAB_TOOLS_LabelTitle_RESID 60046
#define ID_TAB_VIEW 4 
#define ID_TAB_VIEW_LabelTitle_RESID 60047
#define ID_GROUP_HOME 5 
#define ID_GROUP_HOME_LabelTitle_RESID 60048
#define ID_GROUP_TOOLS 6 
#define ID_GROUP_TOOLS_LabelTitle_RESID 60049
#define ID_GROUP_SHOW 7 
#define ID_GROUP_SHOW_LabelTitle_RESID 60050
#define ID_GROUP_HELP 8 
#define ID_GROUP_HELP_LabelTitle_RESID 60051
#define ID_RIBBON_APP_MENU 9 
#define ID_RIBBON_QAT 10 
